# Generated by Django 5.2.6 on 2025-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_alter_newvisit_meeting_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisit',
            name='meeting_stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Closing', 'Closing'), ('Payment Followup', 'Payment followup')], default='Prospecting', max_length=50),
        ),
    ]
