# Generated by Django 5.2.6 on 2025-09-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_alter_newvisit_meeting_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newvisit',
            old_name='payment_collected',
            new_name='is_payment_collected',
        ),
    ]
