# Generated by Django 5.2.6 on 2025-09-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_rename_payment_collected_newvisit_is_payment_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisit',
            name='is_payment_collected',
            field=models.CharField(blank=True, choices=[('Yes-Full', 'Yes-Full'), ('Yes-Partial', 'Yes-Partial'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Won Pending Payment', 'Won Pending Payment'), ('Lost', 'Lost')], default='Open', max_length=30, null=True),
        ),
    ]
