# Generated by Django 5.2.6 on 2025-09-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_alter_newvisit_is_payment_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Closing', 'Closing'), ('Payment Followup', 'Payment followup')], max_length=50)),
                ('contract_outcome', models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=10, null=True)),
                ('is_payment_collected', models.CharField(blank=True, choices=[('Yes-Full', 'Yes-Full'), ('Yes-Partial', 'Yes-Partial'), ('No', 'No')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Won Pending Payment', 'Won Pending Payment'), ('Lost', 'Lost')], max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='visits.newvisit')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
