# Generated by Django 5.2.6 on 2025-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_visitstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstagehistory',
            name='client_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='is_order_final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='products_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
