# Generated by Django 5.2.6 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0009_visitstagehistory_client_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstagehistory',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
