# Generated by Django 5.2.6 on 2025-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_visitstagehistory_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinterested',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
