# Generated by Django 5.2.6 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_productpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpaymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
