# Generated by Django 5.2.6 on 2025-09-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_productpaymenthistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstagehistory',
            name='item_discussed',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
