# Generated by Django 5.2.6 on 2025-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0014_visitstagehistory_item_discussed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisit',
            name='meeting_type',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Phone Call', 'Phone Call')], default='In Person', max_length=20),
        ),
        migrations.AddField(
            model_name='newvisit',
            name='visit_image',
            field=models.ImageField(blank=True, null=True, upload_to='visit_images/'),
        ),
    ]
