# Generated by Django 5.2.6 on 2025-09-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_newvisit_meeting_type_newvisit_visit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvisit',
            name='meeting_type',
            field=models.CharField(choices=[('In Person', 'In Person'), ('Phone Call', 'Phone Call')], max_length=20),
        ),
    ]
