# Generated by Django 5.2.6 on 2025-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_alter_newvisit_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstagehistory',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('In Person', 'In Person'), ('Phone Call', 'Phone Call')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitstagehistory',
            name='visit_image',
            field=models.ImageField(blank=True, null=True, upload_to='visit_stage_images/'),
        ),
    ]
